language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"

service:
  - redis-server

env:
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate

# command to run tests
script:
  - python manage.py test

