language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

service:
  - redis-server

env:
  - DJANGO_VERSION=1.11

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate

# command to run tests
script:
  - python manage.py test

notifications:
  slack:
    rooms:
      - okcomputer-ai:9lpj1KOqS9c5OyxkjGLkcTNn#travis-ci

